# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7a9155d52d7ec51bf94e896661e0b33c55963695fa2b9215bc1b7612d69e37e053ad7e09b2d00ead699f2e42a52a7ec4337c5efa796266da8a035dbfdd5eb43

test:
  secret_key_base: be13b63080fabb63e5bd68910bc43543842373b73b7986edeea1c4ad5c2e46967e3b7922e4b236e4e5ada3747e9642686142ecc0c7c6bdcaf95f1a624caf3496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
